### ISSUE TITLE
adv image projection between steps

### ISSUE THREAD

**Issue by giladcohen** [val-iisc/GAMA-GAT#6]
The Guided_Attack() function is not correct for multi step attacks (step>1).
Between steps, one has to clamp x_adv between (x_natural - eps, x_natural + eps).

I propose to add:

```
def Guided_Attack(model,loss,image, **natural_image**, target,eps=8/255,bounds=[0,1],steps=1,P_out=[],l2_reg=10,alt=1): 
    tar = Variable(target.cuda())
    img = image.cuda()
    eps = eps/steps 
    for step in range(steps):
        img = Variable(img,requires_grad=True)
        zero_gradients(img) 
        out  = model(img)
        R_out = nn.Softmax(dim=1)(out)
        cost = loss(out,tar) + alt*l2_reg*(((P_out - R_out)**2.0).sum(1)).mean(0) 
        cost.backward()
        per = eps * torch.sign(img.grad.data)
        adv = img.data + per.cuda()
        **img = torch.min(torch.max(adv, natural_image - eps), natural_image + eps)**
        img = torch.clamp(adv,bounds[0],bounds[1])
    return img
```

**Comment by SravantiAddepalli** [comment]
Hi @giladcohen 

Thank you for the suggestion. We believe that clamping in every attack step may not be necessary here, since we set eps to eps/steps in L93. Based on this, the overall perturbation can never exceed eps and hence there is no need to clamp in every step.

However, for larger number of steps (>1), an ideal value of eps_step would be 2*eps/steps. We will update this and also incorporate your suggestion of clamping adv between (x_natural - eps, x_natural + eps) in every step. We will update the code after verifying the same.
